### ISSUE TITLE
Using FetchContent instead of ExternalProject in CMake?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/tebako#7]
https://www.scivision.dev/cmake-fetchcontent-vs-external-project/

**Comment by maxirmx** [comment]
The reference  https://www.scivision.dev/cmake-fetchcontent-vs-external-project/  does not mention any advantages of FetchContent over ExternalProject. It just explains the differences.

ExternalProject runs at build time. IMHO this is the right approach to integrate "packaged" products,

FetchContent runs at configure time and INHO this is the right approach to integrate source files.

**Comment by ronaldtse** [comment]
That makes sense. Thanks.
